version: "3.9"

services:
  web:
    build: .
    container_name: flask_todo_app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
    volumes:
      - .:/app

